In [2]:
import numpy as np

# DataTypes and Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1, 2.0, 3.3], 
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [21]:
# Attributes associated with NumPy
a1.shape

(3,)

In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [25]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [26]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
# Creat a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Numpy Arrays

In [31]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [32]:
sample_array.dtype

dtype('int32')

In [33]:
ones = np.ones((2, 3))

In [34]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
ones.dtype

dtype('float64')

In [36]:
type(ones)

numpy.ndarray

In [37]:
zeros = np.zeros((2, 3))

In [38]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
range_array = np.arange(0, 10, 2)

In [40]:
range_array

array([0, 2, 4, 6, 8])

In [42]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 1, 3, 3, 8],
       [3, 2, 7, 7, 2],
       [7, 9, 2, 4, 3]])

In [43]:
random_array.size

15

In [44]:
random_array.shape

(3, 5)

In [47]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.72852088, 0.63654762, 0.75600525],
       [0.65346281, 0.46824279, 0.42945005],
       [0.15063287, 0.9546792 , 0.99140496],
       [0.42777592, 0.67065833, 0.78549899],
       [0.10703   , 0.41360217, 0.56961751]])

In [48]:
random_array2.shape

(5, 3)

In [53]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.1363206 , 0.92615867, 0.12670314],
       [0.59076488, 0.62257251, 0.93464564],
       [0.28489587, 0.00180798, 0.52505459],
       [0.73013933, 0.91691171, 0.04704477],
       [0.17285922, 0.56773102, 0.49409014]])

# NumPy Random Seed

In [70]:
# Pseudo-random numbers
np.random.seed(seed=99999)

random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [65]:
random_array4.shape

(5, 3)

In [76]:
np.random.seed(7)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [79]:
random_array5 = np.random.random((5, 3))
random_array5

array([[0.71932412, 0.41299183, 0.90642327],
       [0.18045162, 0.74111887, 0.42237404],
       [0.42645357, 0.63437987, 0.5229062 ],
       [0.41488598, 0.00142688, 0.09226235],
       [0.70939439, 0.5243456 , 0.69616046]])